version: '3.3'
services:
  db:
    image: postgres:9.6.6
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_pass