package pl.hackathon.plus.feedback.type;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Getter
public enum FeedbackType {
    CASH_REG_FOR_DISABILITIES("CASH_REG_FOR_DISABILITIES"),
    INDUCTION_LOOP_IN_CASH_REG("INDUCTION_LOOP_IN_CASH_REG"),
    INTERCOM("INTERCOM"),
    ALL_CARRIERS_TICKET_OFFICE("ALL_CARRIERS_TICKET_OFFICE"),
    SIGN_LANGUAGE_INFO_STATION("SIGN_LANGUAGE_INFO_STATION"),
    SIGN_LANGUAGE_CASH_REG("SIGN_LANGUAGE_CASH_REG"),
    SUPPORTING_DEVICES("SUPPORTING_DEVICES"),
    WC("WC"),
    ASSISTANT_SERVICE("ASSISTANT_SERVICE"),
    TOUCH_MAP("TOUCH_MAP"),
    P_R_SPACE("P_R_SPACE"),
    HORIZONTAL_MARKINGS("HORIZONTAL_MARKINGS"),
    CHANGING("CHANGING"),
    GUARDIAN_ROOM("GUARDIAN_ROOM");

    private String type;
}
